// Mock data for the DreamWork fundraising & founder-network dashboard.
// Swap this out for a real API layer later — every view reads only from DW_DATA.

const DW_DATA = (() => {
  const founder = {
    name: "Jamie Rowick",
    company: "Uplift360",
    role: "Founder & CEO",
    initials: "JR",
    round: "Seed",
    targetRaise: 2500000,
    raisedSoFar: 1000000,
  };

  // Peer founders in the shared network — used to compute investor overlap
  // ("you and these founders both talk to the same investor").
  const peers = [
    { id: "p1", name: "Alicia Chen", company: "Fernwell", initials: "AC" },
    { id: "p2", name: "Marcus Boyd", company: "Loopstack", initials: "MB" },
    { id: "p3", name: "Priya Nair", company: "Verdant Labs", initials: "PN" },
    { id: "p4", name: "Theo Kastanis", company: "Ridgeline", initials: "TK" },
    { id: "p5", name: "Sena Okoye", company: "Bramblewood", initials: "SO" },
    { id: "p6", name: "Dan Petrov", company: "Kindling AI", initials: "DP" },
    { id: "p7", name: "Wren Iyer", company: "Northbound", initials: "WI" },
  ];

  // direction: how the relationship started
  // status: current pipeline stage
  const investors = [
    {
      id: "i1", name: "Grace Whitfield", firm: "Bluepeak Ventures", type: "VC",
      initials: "GW", color: "#6ee7b7", location: "San Francisco, CA",
      stageFocus: ["Seed", "Series A"], sectors: ["Fintech", "B2B SaaS"],
      checkMin: 250000, checkMax: 1000000, direction: "inbound",
      status: "Term Sheet", warmth: 5, lastActivity: "2026-06-27", amount: 700000,
      introducedBy: null, peerIds: ["p1", "p6"],
      notes: "Reached out after seeing our Demo Day pitch. Moving fast, wants to lead.",
    },
    {
      id: "i2", name: "Marcus Lin", firm: "Anchorpoint Capital", type: "VC",
      initials: "ML", color: "#93c5fd", location: "New York, NY",
      stageFocus: ["Seed"], sectors: ["B2B SaaS", "Marketplaces"],
      checkMin: 100000, checkMax: 500000, direction: "outbound",
      status: "In Diligence", warmth: 4, lastActivity: "2026-06-25",
      introducedBy: "Theo Kastanis (Ridgeline)", peerIds: ["p4"],
      notes: "Second partner meeting done. Requested cohort retention data.",
    },
    {
      id: "i3", name: "Sofia Reyes", firm: "Meridian Fund", type: "VC",
      initials: "SR", color: "#fca5a5", location: "Austin, TX",
      stageFocus: ["Pre-Seed", "Seed"], sectors: ["Fintech"],
      checkMin: 50000, checkMax: 300000, direction: "outbound",
      status: "Meeting Scheduled", warmth: 3, lastActivity: "2026-06-24",
      introducedBy: null, peerIds: ["p3", "p5"],
      notes: "Cold outbound via warm LinkedIn message. First call booked for next week.",
    },
    {
      id: "i4", name: "David Okonkwo", firm: "Harborlight Partners", type: "VC",
      initials: "DO", color: "#fcd34d", location: "Chicago, IL",
      stageFocus: ["Seed", "Series A"], sectors: ["Fintech", "Infra"],
      checkMin: 500000, checkMax: 2000000, direction: "inbound",
      status: "Closed - Won", warmth: 5, lastActivity: "2026-06-10", amount: 500000,
      introducedBy: "Alicia Chen (Fernwell)", peerIds: ["p1", "p2"],
      notes: "Wired $500k as part of the round. Great follow-on potential for A.",
    },
    {
      id: "i5", name: "Elena Petrov", firm: "Cascade Angels", type: "Angel",
      initials: "EP", color: "#a5b4fc", location: "Seattle, WA",
      stageFocus: ["Pre-Seed", "Seed"], sectors: ["B2B SaaS"],
      checkMin: 25000, checkMax: 100000, direction: "outbound",
      status: "Closed - Won", warmth: 5, lastActivity: "2026-06-05", amount: 75000,
      introducedBy: null, peerIds: ["p6"],
      notes: "Fast angel check, wired in 4 days. Very responsive, great operator background.",
    },
    {
      id: "i6", name: "Ben Carruthers", firm: "Northstar Seed", type: "VC",
      initials: "BC", color: "#67e8f9", location: "Boston, MA",
      stageFocus: ["Seed"], sectors: ["Marketplaces", "B2B SaaS"],
      checkMin: 150000, checkMax: 750000, direction: "outbound",
      status: "Passed", warmth: 2, lastActivity: "2026-05-28",
      introducedBy: null, peerIds: ["p2", "p7"],
      notes: "Passed — too early for their thesis, said to circle back at $1M ARR.",
    },
    {
      id: "i7", name: "Nadia Farouk", firm: "Origin Row Capital", type: "VC",
      initials: "NF", color: "#f9a8d4", location: "Los Angeles, CA",
      stageFocus: ["Seed", "Series A"], sectors: ["Fintech"],
      checkMin: 300000, checkMax: 1200000, direction: "inbound",
      status: "In Diligence", warmth: 4, lastActivity: "2026-06-26",
      introducedBy: "Sena Okoye (Bramblewood)", peerIds: ["p5"],
      notes: "Inbound via portfolio founder intro. Legal reviewing our data room now.",
    },
    {
      id: "i8", name: "Owen Marsh", firm: "Fieldstone Ventures", type: "VC",
      initials: "OM", color: "#c4b5fd", location: "Denver, CO",
      stageFocus: ["Series A"], sectors: ["Infra", "B2B SaaS"],
      checkMin: 1000000, checkMax: 3000000, direction: "outbound",
      status: "No Response", warmth: 1, lastActivity: "2026-06-02",
      introducedBy: null, peerIds: [],
      notes: "Cold email sent twice, no response. Likely too early for their check size.",
    },
    {
      id: "i9", name: "Chloe Bergman", firm: "Ridgeback Capital", type: "VC",
      initials: "CB", color: "#6ee7b7", location: "San Francisco, CA",
      stageFocus: ["Seed"], sectors: ["B2B SaaS"],
      checkMin: 200000, checkMax: 600000, direction: "outbound",
      status: "Meeting Scheduled", warmth: 3, lastActivity: "2026-06-23",
      introducedBy: "Dan Petrov (Kindling AI)", peerIds: ["p6", "p4"],
      notes: "First call scheduled via warm intro. She backed two of our peers already.",
    },
    {
      id: "i10", name: "Isaiah Thompson", firm: "Cobblestone Angels", type: "Angel",
      initials: "IT", color: "#fdba74", location: "Miami, FL",
      stageFocus: ["Pre-Seed"], sectors: ["Fintech", "Marketplaces"],
      checkMin: 10000, checkMax: 50000, direction: "inbound",
      status: "Contacted", warmth: 3, lastActivity: "2026-06-20",
      introducedBy: null, peerIds: [],
      notes: "DM'd us on X after our launch thread. Waiting on our reply with deck.",
    },
    {
      id: "i11", name: "Rachel Kim", firm: "Tidewater Fund", type: "VC",
      initials: "RK", color: "#93c5fd", location: "San Francisco, CA",
      stageFocus: ["Seed", "Series A"], sectors: ["Fintech", "B2B SaaS"],
      checkMin: 400000, checkMax: 1500000, direction: "outbound",
      status: "Term Sheet", warmth: 5, lastActivity: "2026-06-28", amount: 750000,
      introducedBy: "Priya Nair (Verdant Labs)", peerIds: ["p3", "p1"],
      notes: "Term sheet in hand, $750k at same terms as Bluepeak. Reviewing with counsel.",
    },
    {
      id: "i12", name: "Malik Johnson", firm: "Ferry Street Capital", type: "VC",
      initials: "MJ", color: "#fca5a5", location: "Atlanta, GA",
      stageFocus: ["Seed"], sectors: ["Marketplaces"],
      checkMin: 100000, checkMax: 400000, direction: "outbound",
      status: "Passed", warmth: 2, lastActivity: "2026-05-15",
      introducedBy: null, peerIds: ["p7"],
      notes: "Passed on sector fit — they've gone all-in on vertical marketplaces only.",
    },
    {
      id: "i13", name: "Hana Suzuki", firm: "Lighthouse Angels", type: "Angel",
      initials: "HS", color: "#fcd34d", location: "Portland, OR",
      stageFocus: ["Pre-Seed", "Seed"], sectors: ["B2B SaaS"],
      checkMin: 15000, checkMax: 75000, direction: "inbound",
      status: "Closed - Won", warmth: 5, lastActivity: "2026-05-30", amount: 25000,
      introducedBy: "Wren Iyer (Northbound)", peerIds: ["p7"],
      notes: "Wired $25k same week as the call. Offered to make 3 more intros.",
    },
    {
      id: "i14", name: "Victor Andrade", firm: "Cormorant Partners", type: "VC",
      initials: "VA", color: "#a5b4fc", location: "New York, NY",
      stageFocus: ["Series A"], sectors: ["Infra"],
      checkMin: 1500000, checkMax: 4000000, direction: "outbound",
      status: "No Response", warmth: 1, lastActivity: "2026-06-01",
      introducedBy: null, peerIds: [],
      notes: "Too early — flagged as an A-round target once we hit $1.5M ARR.",
    },
    {
      id: "i15", name: "Laila Haddad", firm: "Sable Oak Capital", type: "VC",
      initials: "LH", color: "#67e8f9", location: "Chicago, IL",
      stageFocus: ["Seed"], sectors: ["Fintech"],
      checkMin: 250000, checkMax: 900000, direction: "inbound",
      status: "Meeting Scheduled", warmth: 4, lastActivity: "2026-06-26",
      introducedBy: null, peerIds: ["p5", "p3"],
      notes: "Inbound after her associate sourced us from a fintech newsletter roundup.",
    },
    {
      id: "i16", name: "Corey Blackwood", firm: "Millbrook Ventures", type: "VC",
      initials: "CB", color: "#f9a8d4", location: "Boston, MA",
      stageFocus: ["Seed", "Series A"], sectors: ["B2B SaaS", "Infra"],
      checkMin: 300000, checkMax: 1000000, direction: "outbound",
      status: "In Diligence", warmth: 4, lastActivity: "2026-06-24",
      introducedBy: "Marcus Boyd (Loopstack)", peerIds: ["p2"],
      notes: "Reference calls in progress — checking with two of our design partners.",
    },
    {
      id: "i17", name: "Amara Osei", firm: "Solstice Angels Syndicate", type: "Angel",
      initials: "AO", color: "#c4b5fd", location: "Washington, DC",
      stageFocus: ["Pre-Seed", "Seed"], sectors: ["Fintech", "B2B SaaS"],
      checkMin: 20000, checkMax: 150000, direction: "inbound",
      status: "Contacted", warmth: 3, lastActivity: "2026-06-19",
      introducedBy: null, peerIds: ["p1"],
      notes: "Syndicate lead reached out post-podcast appearance. Sending deck this week.",
    },
    {
      id: "i18", name: "Felix Granger", firm: "Wraith Peak Capital", type: "VC",
      initials: "FG", color: "#fdba74", location: "San Francisco, CA",
      stageFocus: ["Seed"], sectors: ["Marketplaces", "Fintech"],
      checkMin: 150000, checkMax: 600000, direction: "outbound",
      status: "Contacted", warmth: 2, lastActivity: "2026-06-18",
      introducedBy: null, peerIds: [],
      notes: "Sent cold outbound with a mutual-connection reference to Rachel Kim.",
    },
    {
      id: "i19", name: "Simone Delacroix", firm: "Rowan Hill Capital", type: "Corporate VC",
      initials: "SD", color: "#6ee7b7", location: "San Francisco, CA",
      stageFocus: ["Series A"], sectors: ["Fintech"],
      checkMin: 750000, checkMax: 2500000, direction: "inbound",
      status: "Meeting Scheduled", warmth: 3, lastActivity: "2026-06-22",
      introducedBy: null, peerIds: ["p4", "p6"],
      notes: "Strategic arm reached out about a potential partnership + investment combo.",
    },
    {
      id: "i20", name: "Julian Voss", firm: "Ember & Co", type: "Family Office",
      initials: "JV", color: "#93c5fd", location: "Palm Beach, FL",
      stageFocus: ["Seed", "Series A"], sectors: ["Fintech", "B2B SaaS"],
      checkMin: 500000, checkMax: 1500000, direction: "outbound",
      status: "Closed - Won", warmth: 5, lastActivity: "2026-06-15", amount: 400000,
      introducedBy: "Alicia Chen (Fernwell)", peerIds: ["p1"],
      notes: "Closed $400k. Family office likes to move quietly but reliably.",
    },
  ];

  // Chronological activity log across the whole network.
  const activity = [
    { id: "a1", date: "2026-06-28", type: "term_sheet", investorId: "i11", text: "Received signed term sheet from Rachel Kim at Tidewater Fund — $750k." },
    { id: "a2", date: "2026-06-27", type: "meeting", investorId: "i1", text: "Partner meeting with Bluepeak Ventures — verbal commitment to lead the round." },
    { id: "a3", date: "2026-06-26", type: "inbound", investorId: "i7", text: "Origin Row Capital sent data room follow-up questions." },
    { id: "a4", date: "2026-06-26", type: "inbound", investorId: "i15", text: "Laila Haddad (Sable Oak) booked an intro call for next Tuesday." },
    { id: "a5", date: "2026-06-25", type: "outbound", investorId: "i2", text: "Sent cohort retention data to Anchorpoint Capital for diligence." },
    { id: "a6", date: "2026-06-24", type: "meeting", investorId: "i9", text: "First call with Chloe Bergman (Ridgeback Capital) via Dan Petrov intro." },
    { id: "a7", date: "2026-06-24", type: "outbound", investorId: "i16", text: "Kicked off reference calls for Millbrook Ventures diligence." },
    { id: "a8", date: "2026-06-23", type: "meeting", investorId: "i3", text: "Booked first call with Sofia Reyes at Meridian Fund." },
    { id: "a9", date: "2026-06-22", type: "inbound", investorId: "i19", text: "Rowan Hill Capital (corporate VC) proposed a partnership + investment call." },
    { id: "a10", date: "2026-06-20", type: "inbound", investorId: "i10", text: "Isaiah Thompson DM'd asking for the deck after our launch thread." },
    { id: "a11", date: "2026-06-19", type: "inbound", investorId: "i17", text: "Amara Osei's syndicate reached out after the fintech podcast episode." },
    { id: "a12", date: "2026-06-18", type: "outbound", investorId: "i18", text: "Sent cold outbound to Felix Granger referencing Rachel Kim connection." },
    { id: "a13", date: "2026-06-15", type: "closed_won", investorId: "i20", text: "Closed $400k from Julian Voss / Ember & Co." },
    { id: "a14", date: "2026-06-10", type: "closed_won", investorId: "i4", text: "Closed $500k from David Okonkwo / Harborlight Partners." },
    { id: "a15", date: "2026-06-05", type: "closed_won", investorId: "i5", text: "Closed $75k angel check from Elena Petrov." },
    { id: "a16", date: "2026-05-30", type: "closed_won", investorId: "i13", text: "Closed $25k from Hana Suzuki, plus 3 offered intros." },
    { id: "a17", date: "2026-05-28", type: "passed", investorId: "i6", text: "Ben Carruthers (Northstar Seed) passed — too early for thesis." },
    { id: "a18", date: "2026-05-15", type: "passed", investorId: "i12", text: "Malik Johnson (Ferry Street) passed — sector fit mismatch." },
    { id: "a19", date: "2026-06-02", type: "outbound", investorId: "i8", text: "Second follow-up email sent to Owen Marsh, no response yet." },
    { id: "a20", date: "2026-06-01", type: "outbound", investorId: "i14", text: "Initial outreach to Victor Andrade at Cormorant Partners." },
  ];

  const pipelineStages = [
    "Contacted",
    "Meeting Scheduled",
    "In Diligence",
    "Term Sheet",
    "Closed - Won",
    "Passed",
  ];

  return { founder, peers, investors, activity, pipelineStages };
})();
